services:
  - type: web
    name: daweb-frontend
    runtime: node
    rootDir: frontend_2do_intento
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: node server.mjs
    envVars:
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production
      - key: API_URL
        value: https://daweb-backend.onrender.com

 